#### VARIABLES
@token=45d7df7a-ab61-4f5e-b2a5-02cc07d92f40
@userId=3a7fec77-0795-4699-9495-cad7814217af
####################################

# The default users for login:
# username: admin or user-{employee number}
# password: adminPassword (admin) & userPassword (common for normal users/employees)

### Login
POST http://localhost:4567/api/login HTTP/1.1
Content-Type: application/json

{
    "username": "user-10028",
    "password": "userPassword"
}

### List all employees with prescribed attributes
GET http://localhost:4567/api/protected/employees HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

### Full employee details by employee number
GET http://localhost:4567/api/protected/employees/10010 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}


### Register new user; protected route
POST http://localhost:4567/api/register HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "username": "10035",
    "password": "userPassword#"
}

### Create new employee
POST http://localhost:4567/api/protected/employees HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "employeeNumber": "10035",
  "lastName": "Dela Cruz",
  "firstName": "Juan",
  "birthday": "08/07/1991",
  "address": "Agapita Building, Metro Manila",
  "phoneNumber": "526-639-512",
  "sssNumber": "20-2987501-6",
  "philhealthNumber": "918460050078",
  "tinNumber": "911-529-713-001",
  "pagibigNumber": "874042259379",
  "status": "Regular",
  "position": "Customer Service and Relations 2",
  "immediateSupervisor": "Reyes, Isabella",
  "basicSalary": 52670,
  "riceSubsidy": 1500,
  "phoneAllowance": 1000,
  "clothingAllowance": 1000,
  "grossSemiMonthlyRate": 26335,
  "hourlyRate": 313.51
}

### Update employee by employee number
PATCH http://localhost:4567/api/protected/employees/10035 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
   "firstName": "Juan",
   "lastName": "Dela Cruz"
}

### Delete employee by employee number
DELETE http://localhost:4567/api/protected/employees/10002 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

### Fetch valid year-month based on the date records in attendance.csv
GET http://localhost:4567/api/protected/monthly-cutoffs HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

### Calculate salary & deductions
GET http://localhost:4567/api/protected/employees/10034/salary?yearMonth=2024-12 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}